### ISSUE TITLE
Generate project with CMake

### ISSUE THREAD

**Issue by antonioborondo** [antonioborondo/pdf_reader#1]
Remove all the Qt project files from the repository and use instead CMake files to generate the project.

**Comment by ZebaSz** [comment]
Hi! I think I can take this up if no one else has :)
Just a question, is there any particular reason to migrate from qmake to CMake?

**Comment by antonioborondo** [comment]
@ZebaSz Yes please, go ahead and thank you 😄 

The main reason to migrate to CMake is because it is widely used nowadays and it would make easier to integrate this project with others in the future.

**Comment by antonioborondo** [comment]
Project generated with CMake: https://github.com/antonioborondo/pdf_reader/tree/cmake
